---
authors:
  rackerlabs:
    name: Rackerlabs
    description: Our collection of Rackers
    avatar: https://github.com/rackerlabs.png
    github: rackerlabs
    twitter: rackspace
    linkedin: rackspace
    website: https://docs.rackspacecloud.com
  cloudnull:
    name: Kevin Carter
    description: Product Director. Developer? Cloud! Caffeine-fueled confidence.
    avatar: https://github.com/cloudnull.png
    github: cloudnull
    twitter: cloudnull
    linkedin: cloudnull
    website: https://cloudnull.io
  robputt:
    name: Robert Putt
    description: Lead Cloud Software Architect @ Rackspace
    avatar: https://robohash.org/robputt
    github: robputt
    linkedin: puttrobert
  jamesdenton:
    name: James Denton
    description: Principal Architect @ Rackspace Technology
    avatar: https://avatars.githubusercontent.com/u/5215642
    github: busterswt
    twitter: jimmdenton
    linkedin: jamesmdenton
    website: https://www.jimmdenton.com/
  dereknoblej:
    name: Derek Noble
    description: Software Developer II @ Rackspace Technology
    avatar: https://avatars.githubusercontent.com/u/48695318
    github: dereknoblej
  pratik705:
    name: Pratik Bandarkar
    description: Cloud Engineer V @ Rackspace Technology
    avatar: https://avatars.githubusercontent.com/pratik705
    github: pratik705
    linkedin: pratik.bandarkar
  sulochan:
    name: Sulochan M Acharya
    description: Cloud Architect @ Rackspace Technology
    avatar: https://avatars.githubusercontent.com/sulochan
    github: sulochan
    twitter: sulo
    linkedin: sulochan
  puni4220:
    name: Punit Shankar Kundal
    description: Cloud Engineer IV @ Rackspace Technology
    avatar: https://avatars.githubusercontent.com/puni4220
    github: puni4220
    linkedin: Punit Kundal
  devx:
    name: Victor Palma
    description: Husban, Dad, Friend, Leader, Coffee Lover.
    avatar: https://github.com/devx.png
    github: devx
    twitter: devx
    linkedin: victorpalma